<?php
/*
  $Id$

  generated by: 
  https://oscompose.com (c)2018

  osCommerce, Open Source E-Commerce Solutions
  http://www.oscommerce.com

  Copyright (c) 2018 osCommerce
  Translation to RU from Fredi. Updated 7/01/2020
  Released under the GNU General Public License
  V1.0 JcM Color Tweak   06-05-2019
  
 

*/

  define('MODULE_HEADER_TAGS_JCM_COLOR_TWEAK_TITLE', 'JcM Color Tweak Выбор цвета');
  define('MODULE_HEADER_TAGS_JCM_COLOR_TWEAK_DESCRIPTION', 'JcM Color Tweak Выбор цвета');

